package com.tyh.dao;

import com.tyh.model.order;
import com.tyh.model.orderExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;



@Mapper
public interface orderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Mar 11 13:44:19 CST 2021
     */
    int countByExample(orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Mar 11 13:44:19 CST 2021
     */
    int deleteByExample(orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Mar 11 13:44:19 CST 2021
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Mar 11 13:44:19 CST 2021
     */
    int insert(order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Mar 11 13:44:19 CST 2021
     */
    int insertSelective(order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Mar 11 13:44:19 CST 2021
     */
    List<order> selectByExample(orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Mar 11 13:44:19 CST 2021
     */
    order selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Mar 11 13:44:19 CST 2021
     */
    int updateByExampleSelective(@Param("record") order record, @Param("example") orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Mar 11 13:44:19 CST 2021
     */
    int updateByExample(@Param("record") order record, @Param("example") orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Mar 11 13:44:19 CST 2021
     */
    int updateByPrimaryKeySelective(order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Mar 11 13:44:19 CST 2021
     */
    int updateByPrimaryKey(order record);
}